- name: ServiceNow CI/CD Instance Scan
    uses: ServiceNow/sncicd-instance-scan@2.0.0
    id: scan
    with:
        scantype: full # point, suite_combo, suite_scoped, suite_update
    env:
        nowUsername: ${{ secrets.NOW_USERNAME }}
        nowPassword: ${{ secrets.NOW_PASSWORD }}
        nowScanInstance: ${{ secrets.NOW_SCAN_INSTANCE }}
